#ifndef MODAPI_GRAPHICS_H
#define MODAPI_GRAPHICS_H

#include <base/vmath.h>

//Item position
enum
{
	MODAPI_ITEMLAYER_UNDER_ITEM=0,
	MODAPI_ITEMLAYER_OVER_ITEM,
	MODAPI_ITEMLAYER_OVER_PLAYER,
	MODAPI_ITEMLAYER_UNDER_PARTICULES,
	MODAPI_ITEMLAYER_OVER_PARTICULES,
	MODAPI_ITEMLAYER_UNDER_NAMEPLATES,
	MODAPI_ITEMLAYER_OVER_NAMEPLATES,
	MODAPI_NUM_ITEMLAYER,
	
	MODAPI_ITEMLAYER_PREPLAYER = MODAPI_ITEMLAYER_UNDER_ITEM,
};

//Options
enum
{
	MODAPI_TEXTALIGN_CENTER = 0,
	MODAPI_TEXTALIGN_RIGHT_BOTTOM,
	MODAPI_TEXTALIGN_RIGHT_CENTER,
	MODAPI_TEXTALIGN_RIGHT_TOP,
	MODAPI_TEXTALIGN_CENTER_TOP,
	MODAPI_TEXTALIGN_LEFT_TOP,
	MODAPI_TEXTALIGN_LEFT_CENTER,
	MODAPI_TEXTALIGN_LEFT_BOTTOM,
	MODAPI_TEXTALIGN_CENTER_BOTTOM,
};

enum
{
	MODAPI_HAND_NONE = 0,
	MODAPI_HAND_BACKHAND,
	MODAPI_HAND_FRONTHAND,
};

enum
{
	MODAPI_TEEALIGN_NONE = 0,
	MODAPI_TEEALIGN_AIM,
	MODAPI_TEEALIGN_HORIZONTAL,
	MODAPI_TEEALIGN_DIRECTION,
	MODAPI_NUM_TEEALIGN,
};

enum
{
	MODAPI_ANIMCYCLETYPE_CLAMP = 0,
	MODAPI_ANIMCYCLETYPE_LOOP,
	MODAPI_NUM_ANIMCYCLETYPE,
};

//Internal resources
enum
{
	MODAPI_IMAGE_GAME = 0,
	MODAPI_IMAGE_PARTICLES,
	MODAPI_IMAGE_DUMMY,
	MODAPI_NUM_IMAGES,
};

enum
{
	MODAPI_SPRITE_WHITESQUARE = 0,
	MODAPI_SPRITE_HAMMER,
	MODAPI_SPRITE_GUN,
	MODAPI_SPRITE_SHOTGUN,
	MODAPI_SPRITE_GRENADE,
	MODAPI_SPRITE_LASER,
	MODAPI_SPRITE_NINJA,
	MODAPI_SPRITE_GUN_MUZZLE1,
	MODAPI_SPRITE_GUN_MUZZLE2,
	MODAPI_SPRITE_GUN_MUZZLE3,
	MODAPI_SPRITE_SHOTGUN_MUZZLE1,
	MODAPI_SPRITE_SHOTGUN_MUZZLE2,
	MODAPI_SPRITE_SHOTGUN_MUZZLE3,
	MODAPI_SPRITE_NINJA_MUZZLE1,
	MODAPI_SPRITE_NINJA_MUZZLE2,
	MODAPI_SPRITE_NINJA_MUZZLE3,
	MODAPI_SPRITE_HAMMER_CURSOR,
	MODAPI_SPRITE_GUN_CURSOR,
	MODAPI_SPRITE_SHOTGUN_CURSOR,
	MODAPI_SPRITE_GRENADE_CURSOR,
	MODAPI_SPRITE_LASER_CURSOR,
	MODAPI_SPRITE_NINJA_CURSOR,
	MODAPI_SPRITE_HOOK_HEAD,
	MODAPI_SPRITE_HOOK_CHAIN,
	
	MODAPI_SPRITE_PART_SPLAT1,
	MODAPI_SPRITE_PART_SPLAT2,
	MODAPI_SPRITE_PART_SPLAT3,
	
	MODAPI_SPRITE_DUMMY_BODYSHADOW,
	MODAPI_SPRITE_DUMMY_BODYCOLOR,
	MODAPI_SPRITE_DUMMY_BODYSHADING,
	MODAPI_SPRITE_DUMMY_BODYOUTLINE,
	MODAPI_SPRITE_DUMMY_MARKING,
	MODAPI_SPRITE_DUMMY_FOOTSHADOW,
	MODAPI_SPRITE_DUMMY_FOOTCOLOR,
	MODAPI_SPRITE_DUMMY_HANDSHADOW,
	MODAPI_SPRITE_DUMMY_HANDCOLOR,
	MODAPI_SPRITE_DUMMY_EYESNORMAL,
	
	MODAPI_NUM_SPRITES,
};

enum
{
	MODAPI_LIST_GUN_MUZZLES = 0,
	MODAPI_LIST_SHOTGUN_MUZZLES,
	MODAPI_LIST_NINJA_MUZZLES,
	MODAPI_LIST_PART_SPLATS,
};

enum
{
	MODAPI_ANIMATION_IDLE_BACKFOOT = 0,
	MODAPI_ANIMATION_IDLE_FRONTFOOT,
	MODAPI_ANIMATION_INAIR_BACKFOOT,
	MODAPI_ANIMATION_INAIR_FRONTFOOT,
	MODAPI_ANIMATION_WALK_BODY,
	MODAPI_ANIMATION_WALK_BACKFOOT,
	MODAPI_ANIMATION_WALK_FRONTFOOT,
	MODAPI_ANIMATION_HAMMERATTACK_WEAPON,
	MODAPI_ANIMATION_GUNATTACK_WEAPON,
	MODAPI_ANIMATION_GUNATTACK_MUZZLE,
	MODAPI_ANIMATION_GUNATTACK_BACKHAND,
	MODAPI_ANIMATION_SHOTGUNATTACK_WEAPON,
	MODAPI_ANIMATION_SHOTGUNATTACK_MUZZLE,
	MODAPI_ANIMATION_SHOTGUNATTACK_BACKHAND,
	MODAPI_ANIMATION_GRENADEATTACK_WEAPON,
	MODAPI_ANIMATION_GRENADEATTACK_BACKHAND,
	MODAPI_ANIMATION_LASERATTACK_WEAPON,
	MODAPI_ANIMATION_NINJAATTACK_WEAPON,
	MODAPI_ANIMATION_NINJAATTACK_MUZZLE,
	MODAPI_ANIMATION_HOOK_CHAIN,
	MODAPI_ANIMATION_HOOK_HEAD,
	MODAPI_ANIMATION_OUTER_LASER,
	MODAPI_ANIMATION_INNER_LASER,
	MODAPI_ANIMATION_OUTER_LASER_HEAD,
	MODAPI_ANIMATION_INNER_LASER_HEAD,
	MODAPI_NUM_ANIMATIONS,
};

enum
{
	MODAPI_TEEANIMATION_IDLE = 0,
	MODAPI_TEEANIMATION_INAIR,
	MODAPI_TEEANIMATION_WALK,
	MODAPI_TEEANIMATION_GUNATTACK,
	MODAPI_TEEANIMATION_SHOTGUNATTACK,
	MODAPI_TEEANIMATION_GRENADEATTACK,
	MODAPI_NUM_TEEANIMATIONS,
};

enum
{
	MODAPI_ATTACH_HAMMER = 0,
	MODAPI_ATTACH_GUN,
	MODAPI_ATTACH_SHOTGUN,
	MODAPI_ATTACH_GRENADE,
	MODAPI_ATTACH_LASER,
	MODAPI_ATTACH_NINJA,
	MODAPI_NUM_ATTACHES,
};

enum
{
	MODAPI_LINESTYLE_HOOK = 0,
	MODAPI_LINESTYLE_LASER,
	MODAPI_NUM_LINESTYLES,
};

enum
{
	MODAPI_SKELETON_TEE = 0,
	MODAPI_SKELETON_HAMMER,
	MODAPI_SKELETON_GUN,
	MODAPI_SKELETON_SHOTGUN,
	MODAPI_NUM_SKELETONS,
};

enum
{
	MODAPI_TEEBONE_BODY = 0,
	MODAPI_TEEBONE_EYES,
	MODAPI_TEEBONE_BACKFOOT,
	MODAPI_TEEBONE_FRONTFOOT,
	MODAPI_TEEBONE_BACKARM,
	MODAPI_TEEBONE_BACKHAND,
	MODAPI_TEEBONE_FRONTARM,
	MODAPI_TEEBONE_FRONTHAND,
	MODAPI_NUM_TEEBONES,
};

enum
{
	MODAPI_TEELAYER_BACKHANDSHADOW = 0,
	MODAPI_TEELAYER_FRONTHANDSHADOW,
	MODAPI_TEELAYER_BACKFOOTSHADOW,
	MODAPI_TEELAYER_BODYSHADOW,
	MODAPI_TEELAYER_FRONTFOOTSHADOW,
	MODAPI_TEELAYER_ATTACH,
	MODAPI_TEELAYER_BACKHAND,
	MODAPI_TEELAYER_FRONTHAND,
	MODAPI_TEELAYER_BACKFOOT,
	MODAPI_TEELAYER_BODY,
	MODAPI_TEELAYER_FRONTFOOT,
	MODAPI_NUM_TEELAYERS,
};

enum
{
	MODAPI_SKELETONSKIN_DUMMY = 0,
	MODAPI_SKELETONSKIN_HAMMER,
	MODAPI_SKELETONSKIN_GUN,
	MODAPI_SKELETONSKIN_SHOTGUN,
	MODAPI_NUM_SKELETONSKINS,
};

enum
{
	MODAPI_SKELETONANIMATION_TEEIDLE = 0,
	MODAPI_SKELETONANIMATION_TEEAIR,
	MODAPI_SKELETONANIMATION_TEEAIR2,
	MODAPI_SKELETONANIMATION_TEEWALK,
	MODAPI_SKELETONANIMATION_HAMMERATTACK,
	MODAPI_SKELETONANIMATION_GUNATTACK,
	MODAPI_SKELETONANIMATION_SHOTGUNATTACK,
	MODAPI_NUM_SKELETONANIMATIONS,
};

enum
{
	MODAPI_SKINPART_BODY=0,
	MODAPI_SKINPART_MARKING,
	MODAPI_SKINPART_DECORATION,
	MODAPI_SKINPART_HANDS,
	MODAPI_SKINPART_FEET,
	MODAPI_SKINPART_EYES,
	MODAPI_NUM_SKINPARTS
};

enum
{
	MODAPI_CHARACTER_TEE=0,
};

//Functions
inline int ModAPI_ColorToInt(const vec4& Color)
{
	int Value = static_cast<int>(Color.r * 255.0f);
	Value += (static_cast<int>(Color.g * 255.0f)<<8);
	Value += (static_cast<int>(Color.b * 255.0f)<<16);
	Value += (static_cast<int>(Color.a * 255.0f)<<24);
	return Value;
}

inline vec4 ModAPI_IntToColor(int Value)
{
	return vec4(
		static_cast<float>(Value & 255)/255.0f,
		static_cast<float>((Value>>8) & 255)/255.0f,
		static_cast<float>((Value>>16) & 255)/255.0f,
		static_cast<float>((Value>>24) & 255)/255.0f
	);
}

#define MODAPI_INTERNAL_ID(id) ((id << 0x1) | 0x1)
#define MODAPI_EXTERNAL_ID(id) (id << 0x1)
#define MODAPI_IS_INTERNAL_ID(id) (id & 0x1)
#define MODAPI_GET_INTERNAL_ID(id) (id >> 0x1)
#define MODAPI_GET_EXTERNAL_ID(id) (id >> 0x1)

#endif
