#ifndef MODAPI_GRAPHICS_H
#define MODAPI_GRAPHICS_H

#include <base/vmath.h>

//Item position
enum
{
	MODAPI_ITEMLAYER_UNDER_ITEM=0,
	MODAPI_ITEMLAYER_OVER_ITEM,
	MODAPI_ITEMLAYER_OVER_PLAYER,
	MODAPI_ITEMLAYER_UNDER_PARTICULES,
	MODAPI_ITEMLAYER_OVER_PARTICULES,
	MODAPI_ITEMLAYER_UNDER_NAMEPLATES,
	MODAPI_ITEMLAYER_OVER_NAMEPLATES,
	MODAPI_NUM_ITEMLAYER,
	
	MODAPI_ITEMLAYER_PREPLAYER = MODAPI_ITEMLAYER_UNDER_ITEM,
};

//Options
enum
{
	MODAPI_LINESTYLE_ANIMATION_NONE = 0,
	MODAPI_LINESTYLE_ANIMATION_SCALEDOWN,
};

enum
{
	MODAPI_LINESTYLE_SPRITETYPE_REPEATED = 0,
};

enum
{
	MODAPI_TEXTALIGN_CENTER = 0,
	MODAPI_TEXTALIGN_RIGHT_BOTTOM,
	MODAPI_TEXTALIGN_RIGHT_CENTER,
	MODAPI_TEXTALIGN_RIGHT_TOP,
	MODAPI_TEXTALIGN_CENTER_TOP,
	MODAPI_TEXTALIGN_LEFT_TOP,
	MODAPI_TEXTALIGN_LEFT_CENTER,
	MODAPI_TEXTALIGN_LEFT_BOTTOM,
	MODAPI_TEXTALIGN_CENTER_BOTTOM,
};

enum
{
	MODAPI_ANIMCYCLETYPE_CLAMP = 0,
	MODAPI_ANIMCYCLETYPE_LOOP,
};

//Internal resources
enum
{
	MODAPI_IMAGE_GAME = 0,
	MODAPI_NUM_IMAGES,
};

enum
{
	MODAPI_NUM_SPRITES = 0,
};

enum
{
	MODAPI_NUM_LINESTYLES = 0,
};

enum
{
	MODAPI_ANIMATION_IDLE_BACKFOOT = 0,
	MODAPI_ANIMATION_IDLE_FRONTFOOT,
	MODAPI_ANIMATION_INAIR_BACKFOOT,
	MODAPI_ANIMATION_INAIR_FRONTFOOT,
	MODAPI_ANIMATION_WALK_BODY,
	MODAPI_ANIMATION_WALK_BACKFOOT,
	MODAPI_ANIMATION_WALK_FRONTFOOT,
	MODAPI_NUM_ANIMATIONS,
};

enum
{
	MODAPI_TEEANIMATION_IDLE = 0,
	MODAPI_TEEANIMATION_INAIR,
	MODAPI_TEEANIMATION_WALK,
	MODAPI_NUM_TEEANIMATIONS,
};

//Functions
inline int ModAPI_ColorToInt(const vec4& Color)
{
	int Value = static_cast<int>(Color.r * 255.0f);
	Value += (static_cast<int>(Color.g * 255.0f)<<8);
	Value += (static_cast<int>(Color.b * 255.0f)<<16);
	Value += (static_cast<int>(Color.a * 255.0f)<<24);
	return Value;
}

inline vec4 ModAPI_IntToColor(int Value)
{
	return vec4(
		static_cast<float>(Value & 255)/255.0f,
		static_cast<float>((Value>>8) & 255)/255.0f,
		static_cast<float>((Value>>16) & 255)/255.0f,
		static_cast<float>((Value>>24) & 255)/255.0f
	);
}

#define MODAPI_INTERNAL_ID(id) ((id << 0x1) | 0x1)
#define MODAPI_EXTERNAL_ID(id) (id << 0x1)
#define MODAPI_IS_INTERNAL_ID(id) (id & 0x1)
#define MODAPI_GET_INTERNAL_ID(id) (id >> 0x1)
#define MODAPI_GET_EXTERNAL_ID(id) (id >> 0x1)

#endif
