#ifndef MODAPI_MAPITEM_H
#define MODAPI_MAPITEM_H

#include <game/mapitems.h>

enum
{
	MODAPI_MAPLAYERTYPE_ENTITIES = LAYERTYPE_QUADS+1,
};
	
enum
{
	MODAPI_ENTITYPOINTTYPE_SPAWN=0,
	MODAPI_ENTITYPOINTTYPE_SPAWN_RED,
	MODAPI_ENTITYPOINTTYPE_SPAWN_BLUE,
	MODAPI_ENTITYPOINTTYPE_FLAGSTAND_RED,
	MODAPI_ENTITYPOINTTYPE_FLAGSTAND_BLUE,
	MODAPI_ENTITYPOINTTYPE_ARMOR,
	MODAPI_ENTITYPOINTTYPE_HEALTH,
	MODAPI_ENTITYPOINTTYPE_WEAPON_SHOTGUN,
	MODAPI_ENTITYPOINTTYPE_WEAPON_GRENADE,
	MODAPI_ENTITYPOINTTYPE_WEAPON_NINJA,
	MODAPI_ENTITYPOINTTYPE_WEAPON_LASER,
	MODAPI_ENTITYPOINTTYPE_WEAPON_GUN,
	MODAPI_ENTITYPOINTTYPE_WEAPON_HAMMER,
};

struct CModAPI_MapEntity_Point
{
	int x;
	int y;
	int m_Type;
};

struct CModAPI_MapItem_LayerEntities
{
	enum { CURRENT_VERSION=1 };

	CMapItemLayer m_Layer;
	int m_Version;
	int m_ModName;
	
	int m_NumPoints;
	int m_PointsData;

	int m_aName[3];
} ;

#endif
