#ifndef MODAPI_WEAPON_H
#define MODAPI_WEAPON_H

#include <generated/protocol.h>

enum
{
	MODAPI_AMMOTYPE_INFINITE = 0,
	MODAPI_AMMOTYPE_INTEGER,
	MODAPI_AMMOTYPE_TIME,
};

enum
{
	MODAPI_WEAPON_HAMMER07 = WEAPON_HAMMER,
	MODAPI_WEAPON_GUN07 = WEAPON_GUN,
	MODAPI_WEAPON_SHOTGUN07 = WEAPON_SHOTGUN,
	MODAPI_WEAPON_GRENADE07 = WEAPON_GRENADE,
	MODAPI_WEAPON_LASER07 = WEAPON_LASER,
	MODAPI_WEAPON_NINJA07 = WEAPON_NINJA,
	MODAPI_NUM_WEAPONS
};


#endif
